version: "3.7"
services:
  grafana:
    image: grafana/grafana:latest
    container_name: my_grafana
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - my-grafana-data:/var/lib/grafana
    networks:
      - default

  node-red:
    image: nodered/node-red:latest
    container_name: my_nodered
    ports:  
      - "1880:1880"
    restart: always
    volumes:
      - my-node-red-data:/data
    networks:
      - default

  influxdb:
    image: influxdb:latest
    container_name: my_influx
    ports:
      - "8086:8086"
    restart: always
    volumes:
      - $PWD/Data/InfluxDatabase:/var/lib/influxdb2
    networks:
      - default

  telegraf:
    image: telegraf:latest
    container_name: my_telegraf
    depends_on:
      - influxdb
    restart: always
    volumes:
      - $PWD/Data/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - default
    

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: my_mqtt
    ports:
      - "1883:1883"
    restart: always
    volumes:
      - $PWD/Data/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - $PWD/Data/mqtt/mosquitto.log:/mosquitto/log/mosquitto.log
    networks:
      - default

volumes:
  my-node-red-data:
  my-grafana-data:

